name: uangku_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 5.1.0
  calendar_appbar: 0.0.6
  dropdown_search: ^0.6.1
  intl: ^0.17.0
  flutter: 
    sdk: flutter
  supabase_flutter: ^1.10.10

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

